mysql:
  host: '124.222.46.195'
  port: 3306
  db: 'Aurora'
  user: 'root'
  password: 'wang'
  charset: 'utf8mb4'
  parseTime: 'True'
  loc: "Local"
  log_level: 'debug'

system:
  host: '0.0.0.0'
  port: 8080
  env: 'release'

logger:
  # 日志等级
  level: 'debug' #panic fatal error warn info debug trace
  # 日志前缀
  prefix: '[Aurora]'
  # 日志目录
  director: 'log'
  # 是否显示行号
  show-line: false
  # 是否显示文件路径
  log-in-console: true

images:
  path: 'static/images'
  size: 20 #上传图片大小 单位MB

minio:
  # 站点
  endpoint: '124.222.46.195:9000'
  # 桶
  bucketName: 'test'
  # 密钥
  accessKeyID: 'wang_test'
  # 密钥密码
  secretAccessKey: 'wang12345678'
  # 是否https连接
  useSSL: false