// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/AuroraPixel",
        "contact": {
            "name": "AuroraPixel",
            "url": "https://github.com/AuroraPixel",
            "email": "wanghanlinlin@126.com"
        },
        "license": {
            "name": "AuroraPixel",
            "url": "https://github.com/AuroraPixel"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/images/page": {
            "get": {
                "description": "分页查询数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片"
                ],
                "summary": "分页列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页容量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/plugins.PageResult"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Data": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.BannerModel"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/images/upload": {
            "post": {
                "description": "图片上传",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片"
                ],
                "summary": "图片上传",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "images",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/imageservice.ImagesVO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "imageservice.ImagesVO": {
            "type": "object",
            "properties": {
                "fileName": {
                    "description": "文件名",
                    "type": "string"
                },
                "isSuccess": {
                    "description": "是否成功",
                    "type": "boolean"
                },
                "message": {
                    "description": "消息内容",
                    "type": "string"
                },
                "path": {
                    "description": "路径",
                    "type": "string"
                }
            }
        },
        "models.BannerModel": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "hash": {
                    "description": "hash值判断图片是否唯一",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "name": {
                    "description": "图片名称",
                    "type": "string"
                },
                "path": {
                    "description": "图片描述",
                    "type": "string"
                },
                "update_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "plugins.PageResult": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "内容"
                },
                "pageCount": {
                    "description": "当前页数量",
                    "type": "integer"
                },
                "pageNum": {
                    "description": "当前页",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每一页容量",
                    "type": "integer"
                },
                "pageTotal": {
                    "description": "页码总数量",
                    "type": "integer"
                },
                "total": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "res.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "AuroraPixel",
	Description:      "AuroraPixel系统API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
