host: 127.0.0.1:8080
info:
  contact:
    email: wanghanlinlin@126.com
    name: AuroraPixel
    url: https://github.com/AuroraPixel
  description: AuroraPixel系统API文档
  license:
    name: AuroraPixel
    url: https://github.com/AuroraPixel
  termsOfService: https://github.com/AuroraPixel
  title: AuroraPixel
  version: "1.0"
paths: {}
swagger: "2.0"
